[unstable]
json-target-spec = true
# These need to be enabled in order to build the kernel, but they cause 
# issues when trying to run tests on the native platform.  Because of this
# I've removed these options from here, and now use a Makefile where these 
# options are explicitly provided on the command line, only for builds.
# Same thing with RUST_FLAGS; they need to be enabled for the actual 
# kernel build, but *not* for tests.
#build-std-features = ["compiler-builtins-mem"]
#build-std = ["core", "compiler_builtins"]

[build]
target = "target.x86_64.json"
